# Generated by Django 4.1.1 on 2022-10-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0011_alter_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
