# Generated by Django 4.1.1 on 2022-10-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
